version: 2.1

jobs:
  build:
   docker:
     - image: cimg/python:3.8
   steps:
     - checkout
     - run: 
         name: setup-python
         command: |
          python3 -m venv venv 
          source venv/bin/activate
          pip install -r requirements.txt

workflows:
  version: 2
  build: 
    jobs:
     - build